Creación en HTML de las páginas que conforman el portal de clínica de litigio penal del ITAM
ITAM-ADSI-2023/Linces-ProyectoFinal pull request #34
Opened 2023-05-01 20:52 UTC by Thiago-whatever

Se crearon y agregaron los elementos correspondientes (conforme a lo requerido) a las siguientes páginas:

- Index (página para dar Inicio de Sesión)
- portalAdmin (página donde se le da la bienvenida al usuarix, cuando éste tiene rol de administrador)
- portalEstudiante (página donde se le da la bienvenida al usuarix, cuando éste tiene rol de estudiante)
- agregarTarea (página donde el administrador crea una tarea para cierto caso y se la asigna a un estudiante(s))
- borradoresCorrecciones (página donde el estudiante puede subir sus archivos para que sean corregidos y revisados; a su vez el administrador puede subir los archivos revisados para que el estudiante vea las correcciones necesarias)
- busquedaCaso (página donde el usuarix puede buscar cierto caso con filtros por tipo de delito, nombre o iniciales del caso, y el estado actual)
- crearCaso (página donde el administrador puede crear el espacio para un nuevo caso)
- detallesDelCaso (página donde se pueden ver todos los detalles de un caso en particular, incluye la lista de tareas, fechas límites, una lista de borradores y correcciones de los archivos pertinentes al caso, entre otras)
- infoCaso (página donde se encuentran los archivos con información pertinente a un caso en específico)
- versionFinal (página donde se deberán subir las versiones finales de los archivos pertinentes a un caso en específico)

*Nota: para tener control sobre el formato a seguir de todas las páginas se incluye un archivo HTML llamado 'paginaBase' el cual incluye un esquema de lo que cada página debería de incluir de manera indispensable.

2023-05-01 21:16 UTC, marielsgtzz requested changes
La estructura de las páginas están muy completas y sí cumplen con los elementos del mock-up.

Para los siguientes pasos de desarrollo es necesario contar con ids en los componentes con los que se va a interactuar, ya sean botones a los que se le van a dar click o labels/textos que van a cambiar según información dinámica.

2023-05-01 21:16 UTC, marielsgtzz commented on PaginasPortal/borradoresCorrecciones.html
> +	<button type="button">Subir Borrador</button>
@AngelAlva falta ponerle id a los botones, tipo
`<button id="btnSubirBorrador">`

2023-05-01 21:16 UTC, marielsgtzz commented on PaginasPortal/detallesDelCaso.html
> +    <select id="estatus-caso" name="estatus-caso">
Creo que vale la pena que el id sea más específico ya que el estatus del caso se muestra en otros lugares también, entonces algo como que
`<input type="text" name="nombre-caso id="txtNombreCasoDetalles"`>

2023-05-01 21:16 UTC, marielsgtzz commented on PaginasPortal/infoCaso.html
> +	<button type="button">Subir Archivo</button>
@AngelAlva igual lo del id del botón

2023-05-01 21:16 UTC, marielsgtzz commented on PaginasPortal/paginaBase.html
> +<!--Página para portal de clínica de litigio penal del ITAM
Ya que ya se hicieron todas las páginas, creo que ya se puede eliminar esta

2023-05-01 21:16 UTC, marielsgtzz commented on PaginasPortal/versionFinal.html
> +	<button type="button">Subir Versión Final</button>
@AngelAlva el mismo comentario del id de los botones

2023-05-02 00:42 UTC, MarianaZapata commented on PaginasPortal/Index.html
> +      <input type="text" id="username" name="username" required /><br />
@AngelAlva aquí pueden agregar placeholder="Nombre de usuario" después de name="username". Es más cuestión de estética, no de funcionalidad. Esto hace más explícito el lugar en donde se tiene que escribir el usuario.
Mismo caso para la contraseña.

2023-05-02 02:03 UTC, marielsgtzz approved these changes
Wup wup

2023-05-02 02:03 UTC, merged